
version: 2.1


jobs:
  preDeploy:
    docker:
      - image: circleci/node:16 
    steps:
      - checkout
      - run:
          name:  npm install dependencies
          command: |
           npm install --save
     - run: 
           name: build
           command: |
              npm run build
workflows:
  deployWorkflow:
    jobs:
      - preDeploy