version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build application
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - node/install-packages
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - node/install-packages
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              npm run deploy
            else
              echo "Not deploying since not on main branch"
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
        
